sonar.projectKey=bckirkup_Scrapiron_and_the_Bear
sonar.organization=bckirkup
sonar.sources=src,scripts,baselines
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
